server:
  port: 8299
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 100MB #单个文件上传大小 默认1MB
      max-request-size: 100MB #一次请求最大携带大小
mybatis:
  type-aliases-package: com.baizhi.czm.entity
  mapper-locations: classpath:com/baizhi/czm/mapper/*Mapper.xml
